# Generated by Django 3.0.8 on 2020-12-07 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20201207_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.ForeignKey(blank=True, default='NON-AC', null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.RoomCategory'),
        ),
    ]
